version: '2'
services:
  postgres:
    container_name: ocelot-saas-postgres
    image: postgres
    ports:
     - 10010:5432
    environment:
     - POSTGRES_USER=ocelot-saas
     - POSTGRES_PASSWORD=ocelot-saas
     - POSTGRES_DB=ocelot-saas
  identity:
    container_name: ocelot-saas-identity
    image: ocelot-saas-identity
    build:
      context: ../identity
    ports:
      - 10001:10000
    links:
      - postgres
    volumes:
      - ../identity/src:/ocelot-saas/pack/src
      - ../identity/secrets.json:/ocelot-saas/var/secrets.json
  inventory:
    container_name: ocelot-saas-inventory
    image: ocelot-saas-inventory
    build:
      context: ../inventory
    ports:
      - 10002:10000
    links:
      - postgres
      - identity
    volumes:
      - ../inventory/src:/ocelot-saas/pack/src
      - ../inventory/secrets.json:/ocelot-saas/var/secrets.json
  actions:
    container_name: ocelot-saas-actions
    image: ocelot-saas-actions
    build:
      context: ../actions
    ports:
      - 10003:10000
    links:
      - postgres
    volumes:
      - ../actions/src:/ocelot-saas/pack/src
      - ../actions/secrets.json:/ocelot-saas/var/secrets.json
  admin:
    container_name: ocelot-saas-admin
    image: ocelot-saas-admin
    build:
      context: ../admin
    ports:
      - 10000:10000
    links:
      - identity
      - inventory
    volumes:
      - ../admin/src:/ocelot-saas/pack/src
      - ../admin/secrets.json:/ocelot-saas/var/secrets.json
  webshop:
    container_name: ocelot-saas-webshop
    image: ocelot-saas-webshop
    build:
      context: ../webshop
    ports:
      - 10100:10000
    links:
      - identity
      - inventory
    volumes:
      - ../webshop/src:/ocelot-saas/pack/src
      - ../webshop/secrets.json:/ocelot-saas/var/secrets.json
