version: '2'
services:
  postgres:
    container_name: ocelot-postgres
    image: postgres
    ports:
     - 10010:5432
    environment:
     - POSTGRES_USER=ocelot
     - POSTGRES_PASSWORD=ocelot
     - POSTGRES_DB=ocelot
  identity-migrate:
    container_name: ocelot-identity-migrate
    image: ocelot-identity
    build:
      context: ../identity
    links:
      - postgres
    volumes:
      - ../identity/bin:/ocelot/pack/bin
      - ../identity/secrets.json:/ocelot/var/secrets.json
    entrypoint: /ocelot/pack/bin/migrate.sh
  identity:
    container_name: ocelot-identity
    image: ocelot-identity
    build:
      context: ../identity
    ports:
      - 10001:10000
    links:
      - postgres
    depends_on:
      - identity-migrate
    volumes:
      - ../identity/src:/ocelot/pack/src
      - ../identity/secrets.json:/ocelot/var/secrets.json
  inventory-migrate:
    container_name: ocelot-inventory-migrate
    image: ocelot-inventory
    build:
      context: ../inventory
    links:
      - postgres
    volumes:
      - ../inventory/bin:/ocelot/pack/bin
      - ../inventory/secrets.json:/ocelot/var/secrets.json
    entrypoint: /ocelot/pack/bin/migrate.sh
  inventory:
    container_name: ocelot-inventory
    image: ocelot-inventory
    build:
      context: ../inventory
    ports:
      - 10002:10000
    links:
      - postgres
      - identity
    depends_on:
      - inventory-migrate
    volumes:
      - ../inventory/src:/ocelot/pack/src
      - ../inventory/secrets.json:/ocelot/var/secrets.json
  admin:
    container_name: ocelot-admin
    image: ocelot-admin
    build:
      context: ../admin
    ports:
      - 10000:10000
    links:
      - identity
      - inventory
    volumes:
      - ../admin/src:/ocelot/pack/src
      - ../admin/secrets.json:/ocelot/var/secrets.json
  webshop:
    container_name: ocelot-webshop
    image: ocelot-webshop
    build:
      context: ../webshop
    ports:
      - 10100:10000
    links:
      - identity
      - inventory
    volumes:
      - ../webshop/src:/ocelot/pack/src
      - ../webshop/secrets.json:/ocelot/var/secrets.json
